# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bst.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(536, 783)
        Form.setWindowOpacity(1.0)
        Form.setStyleSheet("background-color: #222;\n"
"color: #eee;")
        self.rgbImgLabel = QtWidgets.QLabel(Form)
        self.rgbImgLabel.setGeometry(QtCore.QRect(20, 70, 230, 230))
        self.rgbImgLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rgbImgLabel.setAutoFillBackground(False)
        self.rgbImgLabel.setStyleSheet("border: 1px solid #555;\n"
"background: #333;\n"
"color: #ccc;")
        self.rgbImgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rgbImgLabel.setWordWrap(False)
        self.rgbImgLabel.setObjectName("rgbImgLabel")
        self.logBrowser = QtWidgets.QTextBrowser(Form)
        self.logBrowser.setGeometry(QtCore.QRect(20, 370, 471, 71))
        self.logBrowser.setStyleSheet("background: #333;\n"
"color: #ccc;")
        self.logBrowser.setObjectName("logBrowser")
        self.grayImgLabel = QtWidgets.QLabel(Form)
        self.grayImgLabel.setGeometry(QtCore.QRect(260, 70, 230, 230))
        self.grayImgLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.grayImgLabel.setAutoFillBackground(False)
        self.grayImgLabel.setStyleSheet("border: 1px solid #555;\n"
"background: #333;\n"
"color: #ccc;")
        self.grayImgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.grayImgLabel.setWordWrap(False)
        self.grayImgLabel.setObjectName("grayImgLabel")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(20, 480, 471, 281))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1000, 1000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(1000, 1000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.outImgLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.outImgLabel.setGeometry(QtCore.QRect(20, 10, 800, 800))
        self.outImgLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.outImgLabel.setAutoFillBackground(False)
        self.outImgLabel.setStyleSheet("border: 1px solid #555;\n"
"background: #333;\n"
"color: #ccc;")
        self.outImgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.outImgLabel.setWordWrap(False)
        self.outImgLabel.setObjectName("outImgLabel")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 450, 101, 21))
        self.label_2.setObjectName("label_2")
        self.lineEditFilePath = QtWidgets.QLineEdit(Form)
        self.lineEditFilePath.setGeometry(QtCore.QRect(20, 30, 401, 31))
        self.lineEditFilePath.setStyleSheet("background: #333;\n"
"color: #eee;\n"
"border: 1px solid #666;")
        self.lineEditFilePath.setText("")
        self.lineEditFilePath.setObjectName("lineEditFilePath")
        self.btnInputFile = QtWidgets.QPushButton(Form)
        self.btnInputFile.setGeometry(QtCore.QRect(440, 30, 51, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnInputFile.sizePolicy().hasHeightForWidth())
        self.btnInputFile.setSizePolicy(sizePolicy)
        self.btnInputFile.setStyleSheet("background: #333;")
        self.btnInputFile.setObjectName("btnInputFile")
        self.btnConvert = QtWidgets.QPushButton(Form)
        self.btnConvert.setGeometry(QtCore.QRect(320, 320, 61, 31))
        self.btnConvert.setStyleSheet("background: #333;")
        self.btnConvert.setObjectName("btnConvert")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(30, 320, 191, 22))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.spinBoxK = QtWidgets.QSpinBox(self.splitter)
        self.spinBoxK.setMinimum(1)
        self.spinBoxK.setMaximum(16)
        self.spinBoxK.setProperty("value", 4)
        self.spinBoxK.setObjectName("spinBoxK")

        self.retranslateUi(Form)
        self.btnInputFile.clicked.connect(Form.btnInputClick)
        self.btnConvert.clicked.connect(Form.btnConvertClick)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "半色调技术"))
        self.rgbImgLabel.setText(_translate("Form", "image"))
        self.logBrowser.setPlaceholderText(_translate("Form", "输出信息"))
        self.grayImgLabel.setText(_translate("Form", "image"))
        self.outImgLabel.setText(_translate("Form", "image"))
        self.label_2.setText(_translate("Form", "转换结果"))
        self.lineEditFilePath.setPlaceholderText(_translate("Form", "输入图像地址(jpg,png,...)"))
        self.btnInputFile.setText(_translate("Form", "浏览"))
        self.btnConvert.setText(_translate("Form", "转换"))
        self.label.setText(_translate("Form", "bayer矩阵大小"))
